import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "CS 391 MP-4",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style ={{ backgroundColor: '#e91e63' }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
